  
name: Build
on: [push, pull_request]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            asset_name: still_linux
          - os: windows-latest
            asset_name: still.exe
          - os: macos-latest
            asset_name: still
    runs-on: ${{ matrix.os }}

    steps:
      - name: Set up Go 1.14
        uses: actions/setup-go@v2
        with:
          go-version: 1.14

      - name: Check out code
        uses: actions/checkout@v2

      - name: Download dependencies
        run: go mod download

      - name: Run tests
        run: go test ./...

      - name: Build
        run: | 
          go build -v
      
      - name: Move binary to correct location
        if: matrix.os == 'ubuntu-latest'
        run: mv still ${{ matrix.asset_name }}
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: still
          path: ${{ matrix.asset_name }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        if: contains(github.ref, 'tags/v')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload ${{ matrix.name }} Release Asset
        uses: actions/upload-release-asset@v1.0.1
        if: contains(github.ref, 'tags/v')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ matrix.asset_name }}
          asset_name: ${{ matrix.asset_name }}
          asset_content_type: application/octet-stream 